import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { authTables } from '@convex-dev/auth/server';

const applicationTables = {
  userProfiles: defineTable({
    userId: v.id('users'),
    name: v.string(),
    email: v.string(),
    address: v.string(),
    freelanceId: v.string(),
    iban: v.string(),
    bic: v.string(),
    bank: v.string(),
    // Mentions légales facture B2B (alignées sur Job Conciergerie).
    tel: v.optional(v.string()),
    apeCode: v.optional(v.string()), // Code APE/NAF — 4 chiffres + 1 lettre
    immatriculation: v.optional(v.string()), // RCS/RM si activité commerciale/artisanale
    bankAddress: v.optional(v.string()),
  }).index('by_user', ['userId']),

  clients: defineTable({
    userId: v.id('users'),
    name: v.string(),
    contactName: v.string(), // Contact person name for personalized emails
    address: v.string(),
    email: v.string(),
    legalForm: v.string(), // "SARL", "EURL", "Micro-entrepreneur"
    siren: v.optional(v.string()), // 9 chiffres — obligatoire pour un client pro
    tvaNumber: v.optional(v.string()), // N° TVA intracommunautaire
    isActive: v.optional(v.boolean()),
  }).index('by_user', ['userId']),

  services: defineTable({
    userId: v.id('users'),
    label: v.string(),
    defaultPrice: v.number(),
    isActive: v.optional(v.boolean()),
  }).index('by_user', ['userId']),

  invoices: defineTable({
    userId: v.id('users'),
    clientId: v.id('clients'),
    invoiceNumber: v.string(),
    invoiceDate: v.number(),
    // Fin de la prestation — mention obligatoire (dernier jour du mois
    // facturé pour les imports Job Conciergerie).
    serviceEndDate: v.optional(v.number()),
    paymentDate: v.optional(v.number()), // null for sent/draft, set to payment date when paid
    status: v.string(), // "draft", "sent", "paid"
    totalAmount: v.number(),
    items: v.array(
      v.object({
        serviceId: v.id('services'),
        label: v.string(),
        quantity: v.number(),
        price: v.number(),
        discount: v.optional(v.number()), // discount value
        discountUnit: v.optional(v.string()), // "%" or "€"
        discountText: v.optional(v.string()), // description of the discount
        total: v.number(),
      }),
    ),
    pdfStorageId: v.optional(v.id('_storage')), // Stores a PDF generated by the application or a PDF uploaded by the user.
    // Origin of the row — 'job-conciergerie' marks invoices imported by the
    // billing cron; status changes on those are pushed back to JC.
    source: v.optional(v.string()),
  })
    .index('by_user', ['userId'])
    .index('by_user_and_date', ['userId', 'invoiceDate'])
    .index('by_invoice_number', ['invoiceNumber'])
    .index('by_user_and_number', ['userId', 'invoiceNumber']),
};

export default defineSchema({
  ...authTables,
  ...applicationTables,
});
